name: Publish Starters
on: 
  push:
    branches:
      - dev
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python -m pip install -r requirements.txt
      - run: python __main__.py --data-gen --exit-after-data-gen --no-window
      - run: |
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/mcpython4-coding/Index
          copy tools\builds builds
          git add builds
          git commit -m "New push on development"
          git push target master
